# ---
#
# Example properties file for Polites using Databricks.  
#
# ---

# ---
# GENERAL PROPERTIES
# ---

SecretsFileLocation=D:\\_WORKSPACES\\_VAULT\\PolitesSecrets\\databricks-demo-secrets.properties
CdmSchemaName=polites_demo_cdm

# ---
# DATABRICKS REST API PROPERTIES
# ---

DatabricksRestUrl=https://nachc-databricks.cloud.databricks.com/api/2.0
DatabricksUploadRoot=/FileStore/tables/prod
DatabricksFilesRoot=ohdsi/ponos/demo_cdm


