# ---
#
# Example properties file for Polites using Microsoft Sql Server.  
#
# ---

# ---
# GENERAL PARAMETERS
# ---

SecretsFileLocation=D:\\_WORKSPACES\\_VAULT\\PolitesSecrets\\databricks-demo-secrets.properties
CdmSchemaName=polites_demo_cdm


